#!/usr/bin/env python3
"""Extract the embedded RPC catalog from the mod's generated catalog into
mcp-bridge/src/catalog.json (build-time snapshot for the bridge's tool list).
Run from repo root: python mcp-bridge/scripts/extract_catalog.py"""
import re, json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "Mods/GameFeatures/AIMod/Source/AIMod/Private/AIModRpcCatalog.gen.cpp"
OUT = ROOT / "mcp-bridge/src/catalog.json"
text = SRC.read_text(encoding="utf-8")
# The generator splits the catalog across multiple concatenated C++ raw-string
# chunks: TEXT(R"RPCCATALOG(<chunk>)RPCCATALOG") TEXT(R"RPCCATALOG(<chunk>)...
# Join every chunk's content back into one JSON string.
chunks = re.findall(r'R"RPCCATALOG\((.*?)\)RPCCATALOG"', text, re.S)
if not chunks:
    raise SystemExit("could not find RPCCATALOG raw string in " + str(SRC))
cat = json.loads("".join(chunks))
OUT.write_text(json.dumps(cat, indent=1) + "\n", encoding="utf-8")
# Also emit a TS module so the bridge imports it with no JSON-loader/dist-copy fuss.
TS = ROOT / "mcp-bridge/src/catalog.ts"
TS.write_text(
    "// GENERATED by mcp-bridge/scripts/extract_catalog.py - DO NOT EDIT BY HAND.\n"
    "// Snapshot of the mod's world.help catalog (build-time tool list + classification source).\n"
    "import type { Catalog } from \"./catalogTypes.js\";\n"
    "export const CATALOG: Catalog = " + json.dumps(cat, indent=1) + " as Catalog;\n",
    encoding="utf-8")
methods = cat["methods"]
print("methodCount(field)=", cat.get("methodCount"), "parsed=", len(methods))
print("creative=", sorted(x["method"] for x in methods if x.get("creative")))
print("wrote", OUT)
